apiVersion: v1
kind: Service
metadata:
  name: app-go-rest
  namespace: argocd
  labels:
    app: app-go-rest
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: gapp-go-rest
  selector:
    app: app-go-rest
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: argocd
  labels:
    app: app-go-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-go-rest
      tier: frontend
  template:
    metadata:
      labels:
        app: app-go-rest
        tier: frontend
    spec: # Pod spec
      containers:
        - name: go-container
          image: condorl/go-rest:v1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-external-ip
  namespace: argocd
spec:
  podSelector:
    matchLabels:
      app: app-go-rest
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 35.232.116.88/32
