apiVersion: v1
kind: Service
metadata:
  name: app-go-rest
  namespace: argocd
  labels:
    app: app-go-rest
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: gapp-go-rest
  selector:
    app: app-go-rest
    tier: frontend
  type: LoadBalancer
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-go-restv1.0
  namespace: argocd
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: 'Customized with a configmap!'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: argocd
  labels:
    app: app-go-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-go-rest
      tier: frontend
  template:
    metadata:
      labels:
        app: app-go-rest
        tier: frontend
    spec: # Pod spec
      containers:
        - name: go-container
          image: condorl/go-rest:v1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: go-configmapv1.0
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"    # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
